### PR TITLE
Update kernel

### PR DESCRIPTION
**Pull request by Octogonapus**
### Description of the Change

This PR updates the kernel to 3.3.0.

### Motivation

This is blocking #452, though we should update regardless.

### CODE REVIEW

**Comment by kunwarsahni01** [comment]
Did some testing with hardware. Encoder and Potentiometer were functioning properly. But, Button and Ultrasonic were not. I was not getting the proper data printed in the PROS terminal.

**Comment by kunwarsahni01** [comment]
Code that doesn't work when using the expander: 
Button (this code does work when using the internal ADI Ports but does not when using the three wire expander): 
``` 
okapi::ADIButton button(1, 'A'); 
 
while (true) {
 if (button.changedToPressed()) {
      printf("Button pressed\n");
    }
}
```
Ultrasonic (this code does work when using the internal ADI Ports but does not when using the three wire expander): 
```   
okapi::ADIUltrasonic ultra(1, 'A', 'B');

while (true) {
    printf("Ultra Value %f\n", ultra.get());
}
```

**Comment by Octogonapus** [comment]
@kunwarsahni01 Did you get a chance to test this again? If you sent a message in Discord I missed it, sorry.

**Comment by kunwarsahni01** [comment]
Can test tomorrow after 5PM EST when I get in the lab.

**Comment by kunwarsahni01** [comment]
Tested again with new changes: 
Potentiometer is working
Button is working
Ultrasonic is working
Encoder is working

**Comment by Octogonapus** [comment]
@kunwarsahni01 Thanks!

**Pull request merged**
