### PR TITLE
First pass at the API

### PR DESCRIPTION
**Pull request by dcieslak19973**
Have not tested

### Description of the Change

Add `moveDistanceIterative` and `turnAngleIterative` to chassis classes.

See:

https://github.com/OkapiLib/OkapiLib/issues/303

### Motivation

This will be useful for

* Active Brake
* Alignment (Such as Vision Sensor Alignment)
* Angle/Point Seeking

For example:
```
do
{
    robotChassis.turnAngleIterative(0_deg - chassisOdom.theta); // Does 1 step of PID from specified error
    pros::delay(20);
}
while (!robotChassis.isSettled());
```

### Possible Drawbacks

Unclear what the correct behavior for the Integrated chassis type is.  Currently, this implementation passes it down to the corresponding `Async` functions. Could easily throw an exception instead.

### Verification Process

Not yet verified. First commit is to make sure there is alignment on the API. Rough cut at the implementation details.

### Applicable Issues

https://github.com/OkapiLib/OkapiLib/issues/303

### CODE REVIEW

**Comment by dcieslak19973** [comment]
@theol0403 - thoughts?

**Comment by dcieslak19973** [comment]
@theol0403 / @Octogonapus - bump

**Comment by Octogonapus** [comment]
In thinking more about the motivation, I think that all that is really required from the implementation is a method similar to `moveDistanceAsync` that does not reset the PID controllers. Using a method like that, you could walk the target of the PID controllers as needed to track a reference. Selective pausing the PID loop like Theo mentions in #303 could be implemented using the existing `stop` method. The body of `moveDistanceAsync` (after the calls to `reset` and before setting `newMovement`) could be refactored out into `moveDistanceIterative`. The same goes for `turnAngleAsync`.

**Comment by dcieslak19973** [comment]
This is still physically untested.

@Octogonapus  - thanks for the feedback.  I'm not sure that I could exactly refactor as you suggest; I don't think that `stop` would actually pause the PID loop as you may expect - it winds up calling `chassis->stop()` when it gets into `stopAfterSettled()`.

This refactor at least eliminates some duplicated code and has the PID loop actually call "IterativeStep" (protected) functions that the Iterative functions also call, which seems like it adheres to the spirit of this feature.

I thought about providing public `resetForDistanceIterative()` and `resetForTurnIterative()` functions that would reset the PIDs, and the doneLooping/newMovement flags, but that seems like a user might not do right.

**Comment by dcieslak19973** [comment]
This is in a good state for either approval or feedback for changes

**Comment by dcieslak19973** [comment]
@Octogonapus - Any feedback?  If not, good to merge?

**Comment by Octogonapus** [comment]
Closed due to me deleting develop. I would rebase on master but it looks like you didn't enable edits.

I have more time to review this now.

**Pull request closed without merging**
