### PR TITLE
Making branch features/odometry compile again

### PR DESCRIPTION
**Pull request by PixelDust22**
### Description of the Change

Adding "toUnderlyingType(igearset.internalGearset)" as the last argument of ChassisController, SkidSteerModel and ThreeEncoderSkidSteerModel constructors in odomChassisControllerIntegrated.cpp, odomChassisControllerPid.cpp and chassisControllerFactory.cpp

### Benefits

The code now compiles

### Verification Process

- [x] Compiles
- [x] run cppcheck
- [x] run clang-format

### Applicable Issues

#213

### CODE REVIEW

**Comment by Octogonapus** [comment]
@Neo-Zhixing You should merge in the changes from `feature/v3.3.6` which now contains the factory rework.

**Comment by PixelDust22** [comment]
Merge Conflict: Huge amount of merge conflicts in chassisControllerFactory.hpp. I'm not sure what to keep and what to remove.

**Comment by Octogonapus** [comment]
Yep. Throw it out and start again using the new factories.

**Comment by Octogonapus** [comment]
Sorry about this, I don't know why Jonathan had you working on this. I need to think more about how to further compress the chassis controller factory to incorporate odometry.

**Pull request closed without merging**
